=== Odixi/UI-course/src/xmlfiles/houseStructures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.example.org/houseStructures"
xmlns="http://www.example.org/houseStructures" elementFormDefault="qualified">

    <xs:annotation>
        <xs:documentation xml:lang="en">
        House structure schema for UI course project.
        </xs:documentation>
    </xs:annotation>


    <!-- Structure -->
    
    <xs:element name="houses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="house" type="houseDef" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

<!-- Definition of complex elements -->

    <!-- Type: house -->
    <xs:complexType name="houseDef">
        <xs:sequence>
            <xs:element name="housename" type="xs:string" />
            <xs:element name="room" type="roomDef" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <!-- House has to have an unique id -->
        <xs:attribute name="id" use="required" type="xs:ID" />
    </xs:complexType>

    <!-- Type: room -->
    <xs:complexType name="roomDef">
        <xs:sequence>
	        <xs:element name="light" type="smartItem" minOccurs="0" maxOccurs="unbounded" />
	        <xs:element name="sensor" type="smartItem" minOccurs="0" maxOccurs="unbounded" />
	        <xs:element name="appliance" type="smartItem" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <!-- Room has to have an unique id -->
        <xs:attribute name="id" use="required" type="xs:ID" />
    </xs:complexType>
    
    
    <!-- SmartItems -->
    <xs:complexType name="smartItem">
        <xs:sequence>
            <xs:element name="itemName" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" use="required" type="xs:ID" />
    </xs:complexType>
        
</xs:schema>

=== Odixi/UI-course/src/xmlfiles/houseStructures.xml
<?xml version="1.0" encoding="UTF-8"?>
<houses xmlns="htt//www.example.org/houseStructures" schemaLocation="houseStructures.xsd">
  
  <!-- HOUSE -->
  <house id="homeA">
    <housename>Home</housename>
    <room id="ar1">
        <roomname>Living room</roomname>
        <light id="ar1l1">
            <itemName>Ceiling lights</itemName>
        </light>
        <light id="ar1l2">
            <itemName>Floor lamp</itemName>
        </light>
        <sensor id="ar1s1">
            <itemName>Temperature sensor</itemName>
        </sensor>
    </room>     
  </house>
  
  <!-- HOUSE -->
  <house id="">
    
  </house>
  
  <!-- HOUSE -->
  <house id="">
    <housename></housename>
    <room id="">
     
    </room>
    <room id="">
    
    </room>
  </house>
  
  <!-- HOUSE -->
  
  
  
</houses>
