=== Odixi/UI-course/src/xmlfiles/users.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT users (user)+>
<!ELEMENT user (username, password)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== Odixi/UI-course/src/xmlfiles/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "users.dtd" >
<users>
  <user>
    <username>Pilvi</username>
    <password>murmeli</password>
  </user>
  <user>
  	<username>Ville</username>
  	<password>password</password>
  </user>
  <user>
  	<username>Jenni</username>
  	<password>password</password>
  </user>
</users>
